---
- name: Install htop
  hosts: vms
  become: true

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install htop
      ansible.builtin.apt:
        name: htop
        state: present
