---
- name: Ensure group {{ group }} exists
  ansible.builtin.group:
    name: "{{ group }}"
    state: present
  become: true

- name: Ensure {{ ansible_user }} is in {{ group }}
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ group }}"
    append: true
    state: present
  become: true

- name: Add passwordless sudo rule file for {{ group }} in sudoers.d
  ansible.builtin.copy:
    content: |
      # grants passwordless sudo to {{ group }} group
      %admin ALL=(ALL:ALL) NOPASSWD: ALL
    dest: "/etc/sudoers.d/90-{{ group }}-nopasswd"
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  become: true
